[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mythic_metadata = "myThHf7Ec8WEFiVFeUEiuq1KPPmx3udRF7hehPQBaa3"

[programs.devnet]
mythic_metadata = "3jVdbJKJGUMTpGpykpyFyWAG9ry3DRoPqyM48opQa8m6"

[programs.mainnet]
mythic_metadata = "metaThtkusoWYDvHBFXfvc93Z3d8iBeDZ4DVyq8SYVR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
